#!/bin/bash

declare -A board

boardRows=4
boardColumns=4

function initBoard() {
	for i in $(seq 1 $boardRows); do
		for j in $(seq 1 $boardColumns); do
			board[$i,$j]=" "
		done
	done
	for p in $(seq 1 2); do
		# FIXME: Same values of x and y in second iteration.
		local x=$(($RANDOM % $boardColumns + 1))
		local y=$(($RANDOM % $boardRows + 1))
		local n=$(randValue)
		board[$x,$y]=$n
	done
}

function readKey() {
	read -sN1 key
	read -sN1 -t 0.0001 k1
	read -sN1 -t 0.0001 k2
	read -sN1 -t 0.0001 k3
	key+=${k1}${k2}${k3}
	case "$key" in
		$'\e[A')
			echo '↑';
		;;
		$'\e[B')
			echo '↓';
		;;
		$'\e[C')
			echo '→';
		;;
		$'\e[D')
			echo "←";
		;;
		*)
			echo $key
		;;
	esac
}

function moveUp() {
	echo up
}

function moveDown() {
	echo down
}

function moveHorizontally() {
	local row=$1
	local direction=$2
	if [ $direction == 1 ]; then
		local start=1
		local end=$boardColumns
	elif [ $direction == -1 ]; then
		local start=$boardColumns
		local end=1
	else
		echo "FATAL: Invalid direction: $direction" 1>&2
		exit 1
	fi
	for j in $(seq $start $direction $end); do
		if [ "${board[$row,$j]}" != " " ]; then
			local next=$(($j - $direction))
			while [ "${board[$row,$next]}" == " " ]; do
				board[$row,$next]=${board[$row,$(($next + $direction))]}
				board[$row,$(($next + $direction))]=" "
				next=$(($next - $direction))
			done
		fi
	done
}

function moveRight() {
	for i in $(seq 1 $boardRows); do
		moveHorizontally $i -1
	done
}

function moveLeft() {
	for i in $(seq 1 $boardRows); do
		moveHorizontally $i 1
	done
}

function showHelp() {
	echo
	echo "2048 Game written in BASH"
	echo "Diego Lago González <diego.lago.gonzalez@gmail.com>"
	echo
	echo "Keys:"
	echo "Use arrow keys to move numbers."
	echo "Use 'n' to create a new game."
	echo "Use 'q' to quit."
	echo "Use 'h' to show this help."
	echo
}

function processKey() {
	case "$1" in
		"↑")
			moveUp
		;;
		"↓")
			moveDown
		;;
		"→")
			moveRight
		;;
		"←")
			moveLeft
		;;
		"h")
			showHelp
		;;
		"q")
			exit 1
		;;
	esac
}

function randValue() {
	# Should return 2 or 4 (more probability to 2's than 4's).
	echo 2
}

function printBoard() {
	echo "-------------------------"
	for i in $(seq 1 $boardRows); do
		echo -n "|"
		for j in $(seq 1 $boardColumns); do
			printf "%4s " ${board[$i,$j]}
			echo -n "|"
		done
		echo -e "\n-------------------------"
	done
}

function main() {
	initBoard
	while true; do
		printBoard
		key=$(readKey)
		processKey $key
	done
}

main $@
